change: fix the style of menu and options of select
cuweb/rds pull request #445
Opened 2024-11-20 16:23 UTC by m-vojjala

## PR Checklist & Notes

### What type of PR is this? (check all applicable)

- [ ] New component
- [ ] New feature
- [ ] Refactor
- [* ] Bug fix
- [ ] Optimization / Build Tools
- [ ] Documentation Update

### Is this a breaking change?

If yes, please note which project will be impacted.

- [ ] Yes
- [* ] No

### Have you made an entry in the Changelog?

If not, please make an entry or your PR will be declined. Add new entries under the "Unreleased" section of the changelog.

- [ *] Yes
- [ ] No

### Have you made changes to dependencies?

If you've made changes to dependencies please note them here, adding if they've been added, removed or updated, including packages version where applicable.

- [ ] Added
- [ ] Updated
- [ ] Removed
- [ ] Combo of any of the above
- [* ] No

### QA Instructions, Screenshots, Recordings

Please replace this line with instructions on how to test your changes, and if applicable add a note
about any UI changes or if a test should be done on a specific browser. Add any other detail relevant to this PR.

### UI accessibility concerns?

If your PR includes UI changes, please replace this line with details on how
accessibility is impacted and tested. If there are no accessibility concerns delete this section.

2024-11-20 20:00 UTC, troychaplin requested changes

2024-11-20 20:00 UTC, troychaplin commented on lib/components/Form/AutoSuggest/AutoSuggest.tsx
> +      styles={customStyles}
Remove once updates to style.css are done

2024-11-20 21:13 UTC, troychaplin requested changes
We'll always try and use tailwind classes. Easier to be consistent with stuff like shadow-lg, and also easier to search for a property if we want to change them all.

2024-11-20 21:13 UTC, troychaplin commented on lib/components/Form/AutoSuggest/styles.css
> +}
Update these to use @apply with tw classes

2024-11-21 15:03 UTC, troychaplin approved these changes

2024-11-22 20:06 UTC, Singh-Ish approved these changes

2024-11-22 20:06 UTC, merged